# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-master-responder
  namespace: responder
  labels:
    name: locust-responder
    role: master-responder
spec:
  replicas: 1
  selector:
    name: locust-responder
    role: master-responder
  template:
    metadata:
      labels:
        name: locust-responder
        role: master-responder
    spec:
      containers:
        - name: locust
          image: jbarlow801/distributed-load-testing-using-kubernetes:responder
          env:
            - name: LOCUST_MODE
              key: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              key: TARGET_HOST
              value: https://api.int.panda.dpccloud.com
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
